services:
  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: spotfeels
      POSTGRES_PASSWORD: Mudar@123!
    ports:
      - "5432:5432"

volumes:
  postgres_data:
